version: '3.4'

services:
  app:
    container_name: app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: NearbyOrgFinder/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      
  db:
    container_name: db
    image: postgis/postgis:16-3.4
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - ./Database/start_script.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=geodb
      - POSTGRES_PASSWORD=geodb
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
